#!/bin/bash

CONFIG="/etc/rhn/spacewalk-orgclone.conf"
YUMREPO_DIR="/var/satellite/repos"

if [ -z "$1" -o -z "$2" ]
then
    echo "usage: $0 <parentchannel> <prefix>"
    echo "   prefix = prefix of Channel Name (ex. \"Baseline 2012-06-20\")"
    exit 1
fi

parent=$1

childs=`spacecmd -u admin softwarechannel_listchildchannels $parent`

new_parent="$parent-baseline"
echo "+ Cloning Channel $parent to $new_parent"
spacewalk-orgclone-channel.py -f $CONFIG --create -g "$2" -c $parent -d $new_parent 
echo "+ Export Channel to yum repo"
spacewalk-create-yumrepo.py -f $CONFIG -c $new_parent -d $YUMREPO_DIR/$new_parent
echo "+ Creating metadata for channel"
createrepo $YUMREPO_DIR/$new_parent

for child in $childs
do
    echo "+ Doing $child (cloning, yum generating, createrepo)"
    new_child="$child-baseline"
    echo "  - Clone Packages and errata"
    spacewalk-orgclone-channel.py -f $CONFIG --create -g "$2" -e $new_parent -c $child -d $new_child 
    echo "  - Link packages to $YUMREPO_DIR"
    spacewalk-create-yumrepo.py -f $CONFIG -c $new_child -d $YUMREPO_DIR/$new_child
    echo "  - Create yum repo "
    createrepo $YUMREPO_DIR/$new_child
done

